### ISSUE TITLE
 Indian English ASR Challenge dataset request

### ISSUE THREAD

**Issue by kruthikakr** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#12]
Hi 
Can i get the competition IIT-M Speech Lab - Indian English ASR Challenge dataset ? Looking for positive response . 
Thank you

**Comment by GokulNC** [comment]
Hi, you can fill this form which is available in [their website](https://sites.google.com/view/englishasrchallenge/home) to get the download links:
https://docs.google.com/forms/d/e/1FAIpQLSe_daaOrW7sIq488acaryn_56DuWuYI7B8aIpsTPlcU4N2-MQ/viewform

**Comment by kruthikakr** [comment]
Thank you for the response

**Comment by yunxinmengze** [comment]
@kruthikakr  
Hi,Did you get the data of IIT-M Speech Lab - Indian English ASR Challenge dataset? Looking for positive response .

**Comment by kruthikakr** [comment]
Yes , i got the data by filling the form

**Comment by yunxinmengze** [comment]
@kruthikakr 
Thank you for the response.Can you share the data with me! Be deeply grateful.

**Comment by yunxinmengze** [comment]
@kruthikakr 
The access to the data is closed.Can you share the phone.txt of the data with me! Be deeply grateful.
