### ISSUE TITLE
Text file for Opus version

### ISSUE THREAD

**Issue by B-g-Mustafa** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#16]
Where could I find the text for the clips In the Opus version?

**Comment by GokulNC** [comment]
Hi @snakers4 

Can you please help us by commenting here?
Thanks!

**Comment by snakers4** [comment]
If remember correctly there are manifest files in the torrent
Please list the files there to verify

**Comment by snakers4** [comment]
https://academictorrents.com/details/cc9dc56afd3055c7e0f021ec4f1824021558926c

**Comment by B-g-Mustafa** [comment]
Thank you very much, I think I've downloaded the wrong torrent it doesn't
show train and valid data. I'll download this and let you know.

**Comment by B-g-Mustafa** [comment]
Thank you guys, I got the manifest file!
