### ISSUE TITLE
Training Dataset : nptel-train.tar.gz.partap 404 Not Found

### ISSUE THREAD

**Issue by neso613** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#21]
Hi

I found that, specific training dataset link not working
i..e. wget https://zenodo.org/record/4593186/files/nptel-train.tar.gz.partap - Proxy request sent,awaiting response 404 Not Found

Please share the correct link.

@Prem-kumar27 
@GokulNC

**Comment by neso613** [comment]
Please do share the correct link.. because of this missing datalink.. am getting issues while extracting the data.

**Comment by GokulNC** [comment]
It still seems to be working for me, can you please try with a different network maybe?

**Comment by neso613** [comment]
> It still seems to be working for me, can you please try with a different network maybe?

Thanks
