### ISSUE TITLE
NPTEL2020 is part of IIT Madras ASR Challenge 2023?

### ISSUE THREAD

**Issue by neso613** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#22]
Hi
This summer[ IIT Madras launched an ASR challenege on Hindi, Tamil and Indian English.](https://sites.google.com/view/indian-language-asrchallenge/home?authuser=0)

Does this NPTEL2020 data is a sub-set of this?

**Comment by GokulNC** [comment]
Hi, no, this is not in anyway related to IIT-Madras ASR Challenge.
