### ISSUE TITLE
Number of Speakers / Speaker wise split

### ISSUE THREAD

**Issue by balag59** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#3]
Thank you so much for this work! Could you please specify as to how many speakers are present in the dataset. A speaker-wise split would be incredibly helpful as I require single speaker data to train a TTS model using this data. Would this dataset be suitable for that task? I would require roughly 10 hours of single speaker speech with transcripts. Would be incredibly grateful for any help on this matter.

**Comment by Prem-kumar27** [comment]
Hi. We can't provide speaker-wise splits as this dataset was fully-crawled. 
I would suggest you to crawl the small dataset for that. You can download crawl any playlist from [this link](https://www.youtube.com/c/iit/playlists) as each playlist contains videos taught by a single Professor. The quality of subtitles for few courses are not very good. So, check some videos for deciding the course to scrape.

You can also use the [crawler we used](https://github.com/Prem-kumar27/Fast-KTSpeechCrawler) for collecting the dataset.

**Comment by balag59** [comment]
Thanks I'll try what you suggested and see how it goes. Your crawler is especially helpful!
