### ISSUE TITLE
Pure Set transcriptions

### ISSUE THREAD

**Issue by ahazned** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#5]
Hello,

In the Pure Set, "original_txt" and "corrected_txt" folders contain the same transcriptions. I assumed that the "original_txt" folder contains the actual transcriptions (0.14 wer reported for those) and the "corrected_txt" folder contains the transcriptions that are manually anotated by you.  Is my assumption wrong?

**Comment by GokulNC** [comment]
Hi ! Thanks for pointing out the issue.
The issue was with the `original_txt` folder which had the same files as `corrected_txt`.

It's fixed now, and we have re-uploaded the archive.
Please download and check.

Thanks!
