### ISSUE TITLE
Possible to share script for making the nemo manifest

### ISSUE THREAD

**Issue by Hannes1** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#6]
Hi, would it be possible to share the scripts used to make the manifest for Nemo (to train the quartznet) model, I'm using the data crawler given.

**Comment by GokulNC** [comment]
Hello @Hannes1 
Please check the `experiments/` folder of this repo for that script.

**Comment by Hannes1** [comment]
@GokulNC wow, I'm embarrassed😂.
Thanks a lot for the reply👍
