### ISSUE TITLE
Problems downloading

### ISSUE THREAD

**Issue by snakers4** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#7]
Hi,

There are no issues with speed, but I face the following problems:

- It is close to impossible to download the whole chunk (47 GB) without connection interruption;
- If the connection is interrupted, then when I try to resume I get this `HTTP request sent, awaiting response... 429 Too Many Requests`;
- If I use a proxy to avoid this ddos protection rule, then basically I see that the server does not support partial downloads, which is weird for such large files;

In any case I end up with a mix of partial and full files, unable to finish the download after getting 700 GB of data:

![image](https://user-images.githubusercontent.com/12515440/120278980-97b92480-c2be-11eb-8181-9051ea1795f3.png)

Resuming does not work, resuming with proxy does not work.
What can I do in this case?
Can you maybe seed your data via academic torrents?
I can help out by providing my commands I used for my torrents.

**Comment by GokulNC** [comment]
Hi @snakers4 ,

Apologies for the inconvenience caused. Currently we do not have enough funding to keep seeding the large data via Torrents.
Hence we have hosted all our split files on Zenodo.

We would recommend the following, though it could be time-consuming :
1. To find out which files have completed downloading (if you're doubtful), you can verify its MD5 checksum from its Zenodo link, like this: https://zenodo.org/record/4590121
2. For the partially-downloaded files, please try retrying the download. If your connection is not stable from your personal network, please **try downloading from a cloud-based VM** like Azure or GCP/AWS instance.

Currently we are unable to provide any other mirrors apart from this.
Thanks!

**Comment by snakers4** [comment]
> Currently we do not have enough funding to keep seeding the large data via Torrents.

I have an academic torrents account and unlimited gigabit home internet.
If you could help me get the data directly (i.e. via `rsync` over `ssh`) I could just seed for a while.
This is my torrent - https://academictorrents.com/details/95b4cab0f99850e119114c8b6df00193ab5fa34f

> For the partially-downloaded files, please try retrying the download

The problem is that you have some sort of very aggressive fail2ban system that prevents me from continuing any downloads.
`HTTP request sent, awaiting response... 429 Too Many Requests` - this happens if I continue to download any file after the download gets interrupted.

**Comment by snakers4** [comment]
Also if use proxies to continue downloading server tells me that partial downloads are not allowed anyway

**Comment by snakers4** [comment]
I have a partial file, and when I do this I get the following

`wget -c https://zenodo.org/record/4590910/files/nptel-train.tar.gz.partab`

![image](https://user-images.githubusercontent.com/12515440/120637852-14433300-c478-11eb-9873-130b2fc55733.png)

**Comment by nshmyrev** [comment]
> wget -c https://zenodo.org/record/4590910/files/nptel-train.tar.gz.partab

Hey, `wget -c` specifically doesn't work. Try to delete a file and download again, it will download fine.

**Comment by snakers4** [comment]
> Try to delete a file and download again, it will download fine.

Yeah, but this totally defeats the purpose if chunking / partial downloads / etc

**Comment by GokulNC** [comment]
> If you could help me get the data directly, I could just seed for a while.

Sure, that would be great, if you can create an Academic Torrent and seed it.
We can add it as a mirror if you can hit us with a PR :)

Please send me the list of files that you are unable to download. (email: my_user_id @ ai4bharat.org )
I'll try to get those files via my VM and temporarily expose you an FTP endpoint.

**Comment by snakers4** [comment]
> Please send me the list of files that you are unable to download. (email: my_user_id @ ai4bharat.org )
> I'll try to get those files via my VM and temporarily expose you an FTP endpoint.

ok, will do
