### ISSUE TITLE
How to use QuartzNet NEMO's checkpoint

### ISSUE THREAD

**Issue by Vatsalparsaniya** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#9]
Hi, If you could provide a script for inferring a single wav file from the quartznet_nemo_checkpoint.zip, that would be fantastic.
Also, I've never worked with NEMO, so if you could provide setup instructions, that would be extremely helpful.

Thank you.

**Comment by Prem-kumar27** [comment]
Hi @Vatsalparsaniya 

Please check [this notebook](https://github.com/tugstugi/dl-colab-notebooks/blob/master/notebooks/NVidiaQuartzNet.ipynb) for inference instructions.

We used Nemo 0.10.0 and the library has changed a lot now. I think the above notebook uses the Nemo version close to what we used. Hopefully, it should work.

**Comment by Vatsalparsaniya** [comment]
With some minor changes your suggested notebook works for me.

Thank you.
